server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
##打印日志
#logging:
#  level:
#   root: INFO
#   com.itmuch: DEBUG
#显示注册到服务中心的ip与端口
instance:
   prefer-ip-address: true #指定应用的ip，默认为false
   instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#mysql和阿里druid配置
spring:
  application:
    name: zytrade-sevice-mobile    #指定应用的名称建议使用小写
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.1.98:1521:orcl
    #url: jdbc:mysql://localhost/test?useSSL=false&serverTimezone=UTC
    username: proOne
    password: proOne123
    #username: root
   #password: 123456
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

# mybatis配置
mybatis:
  mapper-locations: classpath*:/zytrade.service.mobile/*.xml






